### PR TITLE
fix: Currency UoM

### PR DESCRIPTION
**Pull request by InTheDaylight14**
I was very excited to discover this integration today! Thank you for writing this. 

Because this is a Southern Company integration, only doing business in the US, I think it is okay to make the Units of Measure the $ for the cost related sensors. 

I did not have time to test this on my end tonight, but can later.

### CODE REVIEW

**Comment by Lash-L** [comment]
I think this is all good - as long as test succeed and you have tested it - this will be good to merge

**Comment by Lash-L** [comment]
Can you fix test?

**Comment by phobiac** [comment]
What's needed for this change to be merged in? I know it's a bit old now, but the lack of a unit on the currency trackers means a template sensor is needed to apply a unit and it also means long term statistics aren't tracked with a unit.

**Comment by Lash-L** [comment]
If someone just remakes it on the new codebase version of southern_company, I'd be happy to accept it

**Comment by InTheDaylight14** [comment]
PR #102 created in place of this PR

**Pull request closed without merging**
